/**
 * 英语等级配置 - 定义各等级的词汇表
 * Level 1~3 各扩充至 80+/96+/104+ 词
 * Level 4~6 各扩充至 120+/120+/120+ 词
 * 总计 640+ 词
 */
export const englishGradesConfig = {
  1: {
    name: 'Level 1',
    theme: '颜色·数字·动物·家庭·身体·文具·水果·形状·动作',
    words: [
      // 颜色 (9)
      { en: 'red', cn: '红色', category: 'color', difficulty: 1 },
      { en: 'blue', cn: '蓝色', category: 'color', difficulty: 1 },
      { en: 'green', cn: '绿色', category: 'color', difficulty: 1 },
      { en: 'yellow', cn: '黄色', category: 'color', difficulty: 1 },
      { en: 'white', cn: '白色', category: 'color', difficulty: 1 },
      { en: 'black', cn: '黑色', category: 'color', difficulty: 1 },
      { en: 'brown', cn: '棕色', category: 'color', difficulty: 1 },
      { en: 'purple', cn: '紫色', category: 'color', difficulty: 1 },
      { en: 'pink', cn: '粉色', category: 'color', difficulty: 1 },
      // 数字 (10)
      { en: 'one', cn: '一', category: 'number', difficulty: 1 },
      { en: 'two', cn: '二', category: 'number', difficulty: 1 },
      { en: 'three', cn: '三', category: 'number', difficulty: 1 },
      { en: 'four', cn: '四', category: 'number', difficulty: 1 },
      { en: 'five', cn: '五', category: 'number', difficulty: 1 },
      { en: 'six', cn: '六', category: 'number', difficulty: 1 },
      { en: 'seven', cn: '七', category: 'number', difficulty: 1 },
      { en: 'eight', cn: '八', category: 'number', difficulty: 1 },
      { en: 'nine', cn: '九', category: 'number', difficulty: 1 },
      { en: 'ten', cn: '十', category: 'number', difficulty: 1 },
      // 动物 (10)
      { en: 'cat', cn: '猫', category: 'animal', difficulty: 1 },
      { en: 'dog', cn: '狗', category: 'animal', difficulty: 1 },
      { en: 'bird', cn: '鸟', category: 'animal', difficulty: 1 },
      { en: 'fish', cn: '鱼', category: 'animal', difficulty: 1 },
      { en: 'rabbit', cn: '兔子', category: 'animal', difficulty: 1 },
      { en: 'pig', cn: '猪', category: 'animal', difficulty: 1 },
      { en: 'duck', cn: '鸭子', category: 'animal', difficulty: 1 },
      { en: 'monkey', cn: '猴子', category: 'animal', difficulty: 1 },
      { en: 'panda', cn: '熊猫', category: 'animal', difficulty: 1 },
      { en: 'chicken', cn: '鸡', category: 'animal', difficulty: 1 },
      // 家庭 (7)
      { en: 'father', cn: '父亲', category: 'family', difficulty: 1 },
      { en: 'mother', cn: '母亲', category: 'family', difficulty: 1 },
      { en: 'brother', cn: '兄弟', category: 'family', difficulty: 1 },
      { en: 'sister', cn: '姐妹', category: 'family', difficulty: 1 },
      { en: 'baby', cn: '宝宝', category: 'family', difficulty: 1 },
      { en: 'grandpa', cn: '爷爷/外公', category: 'family', difficulty: 1 },
      { en: 'grandma', cn: '奶奶/外婆', category: 'family', difficulty: 1 },
      // 身体部位 (10)
      { en: 'head', cn: '头', category: 'body', difficulty: 1 },
      { en: 'hand', cn: '手', category: 'body', difficulty: 1 },
      { en: 'eye', cn: '眼睛', category: 'body', difficulty: 1 },
      { en: 'ear', cn: '耳朵', category: 'body', difficulty: 1 },
      { en: 'nose', cn: '鼻子', category: 'body', difficulty: 1 },
      { en: 'mouth', cn: '嘴巴', category: 'body', difficulty: 1 },
      { en: 'face', cn: '脸', category: 'body', difficulty: 1 },
      { en: 'arm', cn: '手臂', category: 'body', difficulty: 1 },
      { en: 'leg', cn: '腿', category: 'body', difficulty: 1 },
      { en: 'foot', cn: '脚', category: 'body', difficulty: 1 },
      // 文具 (8)
      { en: 'bag', cn: '书包', category: 'stationery', difficulty: 1 },
      { en: 'pen', cn: '钢笔', category: 'stationery', difficulty: 1 },
      { en: 'ruler', cn: '尺子', category: 'stationery', difficulty: 1 },
      { en: 'eraser', cn: '橡皮', category: 'stationery', difficulty: 1 },
      { en: 'crayon', cn: '蜡笔', category: 'stationery', difficulty: 1 },
      { en: 'pencil', cn: '铅笔', category: 'stationery', difficulty: 1 },
      { en: 'book', cn: '书', category: 'stationery', difficulty: 1 },
      { en: 'sharpener', cn: '卷笔刀', category: 'stationery', difficulty: 1 },
      // 水果 (8)
      { en: 'orange', cn: '橙子', category: 'fruit', difficulty: 1 },
      { en: 'banana', cn: '香蕉', category: 'fruit', difficulty: 1 },
      { en: 'pear', cn: '梨', category: 'fruit', difficulty: 1 },
      { en: 'grape', cn: '葡萄', category: 'fruit', difficulty: 1 },
      { en: 'watermelon', cn: '西瓜', category: 'fruit', difficulty: 1 },
      { en: 'apple', cn: '苹果', category: 'fruit', difficulty: 1 },
      { en: 'strawberry', cn: '草莓', category: 'fruit', difficulty: 1 },
      { en: 'lemon', cn: '柠檬', category: 'fruit', difficulty: 1 },
      // 形状 (4)
      { en: 'circle', cn: '圆形', category: 'shape', difficulty: 1 },
      { en: 'square', cn: '正方形', category: 'shape', difficulty: 1 },
      { en: 'triangle', cn: '三角形', category: 'shape', difficulty: 1 },
      { en: 'star', cn: '星星', category: 'shape', difficulty: 1 },
      // 动作 (6)
      { en: 'run', cn: '跑', category: 'action', difficulty: 1 },
      { en: 'jump', cn: '跳', category: 'action', difficulty: 1 },
      { en: 'sing', cn: '唱歌', category: 'action', difficulty: 1 },
      { en: 'dance', cn: '跳舞', category: 'action', difficulty: 1 },
      { en: 'read', cn: '阅读', category: 'action', difficulty: 1 },
      { en: 'draw', cn: '画画', category: 'action', difficulty: 1 },
      // 常见短语 (11)
      { en: 'good morning', cn: '早上好', category: 'phrase', difficulty: 1, phrase: 'Good morning!', sentence: 'Good morning, teacher!' },
      { en: 'good night', cn: '晚安', category: 'phrase', difficulty: 1, phrase: 'Good night!', sentence: 'Good night, Mom.' },
      { en: 'thank you', cn: '谢谢', category: 'phrase', difficulty: 1, phrase: 'Thank you!', sentence: 'Thank you very much.' },
      { en: 'hello', cn: '你好', category: 'phrase', difficulty: 1, phrase: 'Hello!', sentence: 'Hello, my name is Tom.' },
      { en: 'goodbye', cn: '再见', category: 'phrase', difficulty: 1, phrase: 'Goodbye!', sentence: 'Goodbye, see you tomorrow.' },
      { en: 'yes', cn: '是的', category: 'phrase', difficulty: 1, phrase: 'Yes.', sentence: 'Yes, I can.' },
      { en: 'no', cn: '不', category: 'phrase', difficulty: 1, phrase: 'No.', sentence: 'No, I don\'t.' },
      { en: 'sorry', cn: '对不起', category: 'phrase', difficulty: 1, phrase: 'Sorry.', sentence: 'Sorry, I\'m late.' },
      { en: 'please', cn: '请', category: 'phrase', difficulty: 1, phrase: 'Please.', sentence: 'Please sit down.' },
      { en: 'how are you', cn: '你好吗', category: 'phrase', difficulty: 1, phrase: 'How are you?', sentence: 'How are you today?' },
      { en: 'i am fine', cn: '我很好', category: 'phrase', difficulty: 1, phrase: 'I am fine.', sentence: 'I am fine, thank you.' }
    ]
  },

  2: {
    name: 'Level 2',
    theme: '学校·食物·服装·天气·玩具·房间·星期·动物扩展·方位·动作短语',
    words: [
      // 学校 (10)
      { en: 'school', cn: '学校', category: 'school', difficulty: 2 },
      { en: 'teacher', cn: '老师', category: 'school', difficulty: 2 },
      { en: 'student', cn: '学生', category: 'school', difficulty: 2 },
      { en: 'pencil', cn: '铅笔', category: 'school', difficulty: 2 },
      { en: 'classroom', cn: '教室', category: 'school', difficulty: 2 },
      { en: 'desk', cn: '书桌', category: 'school', difficulty: 2 },
      { en: 'chair', cn: '椅子', category: 'school', difficulty: 2 },
      { en: 'blackboard', cn: '黑板', category: 'school', difficulty: 2 },
      { en: 'door', cn: '门', category: 'school', difficulty: 2 },
      { en: 'window', cn: '窗户', category: 'school', difficulty: 2 },
      // 食物 (10)
      { en: 'apple', cn: '苹果', category: 'food', difficulty: 2 },
      { en: 'bread', cn: '面包', category: 'food', difficulty: 2 },
      { en: 'milk', cn: '牛奶', category: 'food', difficulty: 2 },
      { en: 'egg', cn: '鸡蛋', category: 'food', difficulty: 2 },
      { en: 'rice', cn: '米饭', category: 'food', difficulty: 2 },
      { en: 'meat', cn: '肉', category: 'food', difficulty: 2 },
      { en: 'water', cn: '水', category: 'food', difficulty: 2 },
      { en: 'juice', cn: '果汁', category: 'food', difficulty: 2 },
      { en: 'cake', cn: '蛋糕', category: 'food', difficulty: 2 },
      { en: 'candy', cn: '糖果', category: 'food', difficulty: 2 },
      // 服装 (8)
      { en: 'shirt', cn: '衬衫', category: 'clothing', difficulty: 2 },
      { en: 'shoes', cn: '鞋子', category: 'clothing', difficulty: 2 },
      { en: 'hat', cn: '帽子', category: 'clothing', difficulty: 2 },
      { en: 'coat', cn: '外套', category: 'clothing', difficulty: 2 },
      { en: 'socks', cn: '袜子', category: 'clothing', difficulty: 2 },
      { en: 'pants', cn: '裤子', category: 'clothing', difficulty: 2 },
      { en: 'dress', cn: '连衣裙', category: 'clothing', difficulty: 2 },
      { en: 'jacket', cn: '夹克', category: 'clothing', difficulty: 2 },
      // 天气 (8)
      { en: 'sunny', cn: '晴天', category: 'weather', difficulty: 2 },
      { en: 'rainy', cn: '下雨', category: 'weather', difficulty: 2 },
      { en: 'cloudy', cn: '多云', category: 'weather', difficulty: 2 },
      { en: 'windy', cn: '有风', category: 'weather', difficulty: 2 },
      { en: 'snowy', cn: '下雪', category: 'weather', difficulty: 2 },
      { en: 'hot', cn: '热的', category: 'weather', difficulty: 2 },
      { en: 'cold', cn: '冷的', category: 'weather', difficulty: 2 },
      { en: 'warm', cn: '温暖的', category: 'weather', difficulty: 2 },
      // 玩具 (8)
      { en: 'doll', cn: '娃娃', category: 'toy', difficulty: 2 },
      { en: 'ball', cn: '球', category: 'toy', difficulty: 2 },
      { en: 'kite', cn: '风筝', category: 'toy', difficulty: 2 },
      { en: 'toy', cn: '玩具', category: 'toy', difficulty: 2 },
      { en: 'game', cn: '游戏', category: 'toy', difficulty: 2 },
      { en: 'teddy bear', cn: '泰迪熊', category: 'toy', difficulty: 2 },
      { en: 'puzzle', cn: '拼图', category: 'toy', difficulty: 2 },
      { en: 'robot', cn: '机器人', category: 'toy', difficulty: 2 },
      // 房间 (8)
      { en: 'room', cn: '房间', category: 'room', difficulty: 2 },
      { en: 'bedroom', cn: '卧室', category: 'room', difficulty: 2 },
      { en: 'living room', cn: '客厅', category: 'room', difficulty: 2 },
      { en: 'kitchen', cn: '厨房', category: 'room', difficulty: 2 },
      { en: 'bathroom', cn: '卫生间', category: 'room', difficulty: 2 },
      { en: 'bed', cn: '床', category: 'room', difficulty: 2 },
      { en: 'table', cn: '桌子', category: 'room', difficulty: 2 },
      { en: 'sofa', cn: '沙发', category: 'room', difficulty: 2 },
      // 星期 (7)
      { en: 'monday', cn: '星期一', category: 'week', difficulty: 2 },
      { en: 'tuesday', cn: '星期二', category: 'week', difficulty: 2 },
      { en: 'wednesday', cn: '星期三', category: 'week', difficulty: 2 },
      { en: 'thursday', cn: '星期四', category: 'week', difficulty: 2 },
      { en: 'friday', cn: '星期五', category: 'week', difficulty: 2 },
      { en: 'saturday', cn: '星期六', category: 'week', difficulty: 2 },
      { en: 'sunday', cn: '星期日', category: 'week', difficulty: 2 },
      // 动物扩展 (7)
      { en: 'horse', cn: '马', category: 'animal', difficulty: 2 },
      { en: 'sheep', cn: '绵羊', category: 'animal', difficulty: 2 },
      { en: 'cow', cn: '奶牛', category: 'animal', difficulty: 2 },
      { en: 'bear', cn: '熊', category: 'animal', difficulty: 2 },
      { en: 'elephant', cn: '大象', category: 'animal', difficulty: 2 },
      { en: 'tiger', cn: '老虎', category: 'animal', difficulty: 2 },
      { en: 'lion', cn: '狮子', category: 'animal', difficulty: 2 },
      // 方位 (8)
      { en: 'in', cn: '在…里面', category: 'position', difficulty: 2 },
      { en: 'on', cn: '在…上面', category: 'position', difficulty: 2 },
      { en: 'under', cn: '在…下面', category: 'position', difficulty: 2 },
      { en: 'near', cn: '在…附近', category: 'position', difficulty: 2 },
      { en: 'behind', cn: '在…后面', category: 'position', difficulty: 2 },
      { en: 'beside', cn: '在…旁边', category: 'position', difficulty: 2 },
      { en: 'in front of', cn: '在…前面', category: 'position', difficulty: 2 },
      { en: 'between', cn: '在…之间', category: 'position', difficulty: 2 },
      // 动作短语 (10)
      { en: 'get up', cn: '起床', category: 'verb_phrase', difficulty: 2, phrase: 'get up', sentence: 'I get up at six o\'clock.' },
      { en: 'go to school', cn: '上学', category: 'verb_phrase', difficulty: 2, phrase: 'go to school', sentence: 'I go to school by bus.' },
      { en: 'go home', cn: '回家', category: 'verb_phrase', difficulty: 2, phrase: 'go home', sentence: 'Let\'s go home together.' },
      { en: 'have breakfast', cn: '吃早餐', category: 'verb_phrase', difficulty: 2, phrase: 'have breakfast', sentence: 'I have breakfast at seven.' },
      { en: 'have lunch', cn: '吃午餐', category: 'verb_phrase', difficulty: 2, phrase: 'have lunch', sentence: 'We have lunch at school.' },
      { en: 'have dinner', cn: '吃晚餐', category: 'verb_phrase', difficulty: 2, phrase: 'have dinner', sentence: 'We have dinner together.' },
      { en: 'watch TV', cn: '看电视', category: 'verb_phrase', difficulty: 2, phrase: 'watch TV', sentence: 'I watch TV in the evening.' },
      { en: 'play football', cn: '踢足球', category: 'verb_phrase', difficulty: 2, phrase: 'play football', sentence: 'The boys play football after school.' },
      { en: 'listen to music', cn: '听音乐', category: 'verb_phrase', difficulty: 2, phrase: 'listen to music', sentence: 'She likes to listen to music.' },
      { en: 'do homework', cn: '做作业', category: 'verb_phrase', difficulty: 2, phrase: 'do homework', sentence: 'I do my homework every day.' },
      // 常见短语 (12)
      { en: 'excuse me', cn: '打扰一下', category: 'phrase', difficulty: 2, phrase: 'Excuse me.', sentence: 'Excuse me, where is the park?' },
      { en: 'come in', cn: '请进', category: 'phrase', difficulty: 2, phrase: 'Come in, please.', sentence: 'Come in and sit down.' },
      { en: 'sit down', cn: '坐下', category: 'phrase', difficulty: 2, phrase: 'Sit down, please.', sentence: 'Please sit down.' },
      { en: 'stand up', cn: '起立', category: 'phrase', difficulty: 2, phrase: 'Stand up!', sentence: 'Stand up, please.' },
      { en: 'well done', cn: '做得好', category: 'phrase', difficulty: 2, phrase: 'Well done!', sentence: 'Well done, you got it right!' },
      { en: 'you are welcome', cn: '不客气', category: 'phrase', difficulty: 2, phrase: 'You\'re welcome.', sentence: 'Thank you! — You\'re welcome.' },
      { en: 'see you', cn: '再见', category: 'phrase', difficulty: 2, phrase: 'See you!', sentence: 'See you tomorrow!' },
      { en: 'here you are', cn: '给你', category: 'phrase', difficulty: 2, phrase: 'Here you are.', sentence: 'Here you are, your book.' },
      { en: 'have a try', cn: '试一下', category: 'phrase', difficulty: 2, phrase: 'Have a try.', sentence: 'Don\'t be afraid, have a try.' },
      { en: 'take a break', cn: '休息一下', category: 'phrase', difficulty: 2, phrase: 'Take a break.', sentence: 'Let\'s take a break.' },
      { en: 'come on', cn: '加油', category: 'phrase', difficulty: 2, phrase: 'Come on!', sentence: 'Come on, you can do it!' },
      { en: 'hurry up', cn: '快点', category: 'phrase', difficulty: 2, phrase: 'Hurry up!', sentence: 'Hurry up, we are late!' }
    ]
  },

  3: {
    name: 'Level 3',
    theme: '动词·形容词·方位·时间·职业·运动·食物扩展·副词·天气扩展',
    words: [
      // 动词 (12)
      { en: 'get up', cn: '起床', category: 'verb', difficulty: 3 },
      { en: 'go to school', cn: '上学', category: 'verb', difficulty: 3 },
      { en: 'have dinner', cn: '吃晚饭', category: 'verb', difficulty: 3 },
      { en: 'play football', cn: '踢足球', category: 'verb', difficulty: 3 },
      { en: 'watch TV', cn: '看电视', category: 'verb', difficulty: 3 },
      { en: 'cook', cn: '做饭', category: 'verb', difficulty: 3 },
      { en: 'clean', cn: '打扫', category: 'verb', difficulty: 3 },
      { en: 'wash', cn: '洗', category: 'verb', difficulty: 3 },
      { en: 'help', cn: '帮助', category: 'verb', difficulty: 3 },
      { en: 'play', cn: '玩', category: 'verb', difficulty: 3 },
      { en: 'study', cn: '学习', category: 'verb', difficulty: 3 },
      { en: 'swim', cn: '游泳', category: 'verb', difficulty: 3 },
      // 形容词 (12)
      { en: 'happy', cn: '高兴的', category: 'adjective', difficulty: 3 },
      { en: 'beautiful', cn: '美丽的', category: 'adjective', difficulty: 3 },
      { en: 'strong', cn: '强壮的', category: 'adjective', difficulty: 3 },
      { en: 'clever', cn: '聪明的', category: 'adjective', difficulty: 3 },
      { en: 'brave', cn: '勇敢的', category: 'adjective', difficulty: 3 },
      { en: 'tall', cn: '高的', category: 'adjective', difficulty: 3 },
      { en: 'short', cn: '矮的', category: 'adjective', difficulty: 3 },
      { en: 'big', cn: '大的', category: 'adjective', difficulty: 3 },
      { en: 'small', cn: '小的', category: 'adjective', difficulty: 3 },
      { en: 'long', cn: '长的', category: 'adjective', difficulty: 3 },
      { en: 'new', cn: '新的', category: 'adjective', difficulty: 3 },
      { en: 'old', cn: '旧的/老的', category: 'adjective', difficulty: 3 },
      // 方位 (8)
      { en: 'left', cn: '左边', category: 'direction', difficulty: 3 },
      { en: 'right', cn: '右边', category: 'direction', difficulty: 3 },
      { en: 'front', cn: '前面', category: 'direction', difficulty: 3 },
      { en: 'back', cn: '后面', category: 'direction', difficulty: 3 },
      { en: 'middle', cn: '中间', category: 'direction', difficulty: 3 },
      { en: 'up', cn: '向上', category: 'direction', difficulty: 3 },
      { en: 'down', cn: '向下', category: 'direction', difficulty: 3 },
      { en: 'around', cn: '周围', category: 'direction', difficulty: 3 },
      // 时间 (8)
      { en: 'morning', cn: '早晨', category: 'time', difficulty: 3 },
      { en: 'afternoon', cn: '下午', category: 'time', difficulty: 3 },
      { en: 'evening', cn: '傍晚', category: 'time', difficulty: 3 },
      { en: 'today', cn: '今天', category: 'time', difficulty: 3 },
      { en: 'tomorrow', cn: '明天', category: 'time', difficulty: 3 },
      { en: 'yesterday', cn: '昨天', category: 'time', difficulty: 3 },
      { en: 'now', cn: '现在', category: 'time', difficulty: 3 },
      { en: 'later', cn: '稍后', category: 'time', difficulty: 3 },
      // 职业 (10)
      { en: 'doctor', cn: '医生', category: 'occupation', difficulty: 3 },
      { en: 'nurse', cn: '护士', category: 'occupation', difficulty: 3 },
      { en: 'teacher', cn: '老师', category: 'occupation', difficulty: 3 },
      { en: 'driver', cn: '司机', category: 'occupation', difficulty: 3 },
      { en: 'policeman', cn: '警察', category: 'occupation', difficulty: 3 },
      { en: 'farmer', cn: '农民', category: 'occupation', difficulty: 3 },
      { en: 'worker', cn: '工人', category: 'occupation', difficulty: 3 },
      { en: 'singer', cn: '歌手', category: 'occupation', difficulty: 3 },
      { en: 'dancer', cn: '舞者', category: 'occupation', difficulty: 3 },
      { en: 'cook (n.)', cn: '厨师', category: 'occupation', difficulty: 3 },
      // 运动 (8)
      { en: 'football', cn: '足球', category: 'sport', difficulty: 3 },
      { en: 'basketball', cn: '篮球', category: 'sport', difficulty: 3 },
      { en: 'volleyball', cn: '排球', category: 'sport', difficulty: 3 },
      { en: 'swimming', cn: '游泳', category: 'sport', difficulty: 3 },
      { en: 'running', cn: '跑步', category: 'sport', difficulty: 3 },
      { en: 'skipping', cn: '跳绳', category: 'sport', difficulty: 3 },
      { en: 'table tennis', cn: '乒乓球', category: 'sport', difficulty: 3 },
      { en: 'badminton', cn: '羽毛球', category: 'sport', difficulty: 3 },
      // 食物扩展 (10)
      { en: 'noodles', cn: '面条', category: 'food', difficulty: 3 },
      { en: 'dumplings', cn: '饺子', category: 'food', difficulty: 3 },
      { en: 'soup', cn: '汤', category: 'food', difficulty: 3 },
      { en: 'fish', cn: '鱼', category: 'food', difficulty: 3 },
      { en: 'chicken', cn: '鸡肉', category: 'food', difficulty: 3 },
      { en: 'vegetables', cn: '蔬菜', category: 'food', difficulty: 3 },
      { en: 'fruit', cn: '水果', category: 'food', difficulty: 3 },
      { en: 'sandwich', cn: '三明治', category: 'food', difficulty: 3 },
      { en: 'hamburger', cn: '汉堡包', category: 'food', difficulty: 3 },
      { en: 'pizza', cn: '比萨', category: 'food', difficulty: 3 },
      // 副词 (8)
      { en: 'always', cn: '总是', category: 'adverb', difficulty: 3 },
      { en: 'usually', cn: '通常', category: 'adverb', difficulty: 3 },
      { en: 'often', cn: '经常', category: 'adverb', difficulty: 3 },
      { en: 'sometimes', cn: '有时', category: 'adverb', difficulty: 3 },
      { en: 'never', cn: '从不', category: 'adverb', difficulty: 3 },
      { en: 'very', cn: '非常', category: 'adverb', difficulty: 3 },
      { en: 'too', cn: '太/也', category: 'adverb', difficulty: 3 },
      { en: 'also', cn: '也', category: 'adverb', difficulty: 3 },
      // 天气扩展 (6)
      { en: 'weather', cn: '天气', category: 'weather', difficulty: 3 },
      { en: 'rain', cn: '雨', category: 'weather', difficulty: 3, sentence: 'It often rains here in summer.' },
      { en: 'snow', cn: '雪', category: 'weather', difficulty: 3, sentence: 'Look! It is snowing outside.' },
      { en: 'wind', cn: '风', category: 'weather', difficulty: 3 },
      { en: 'foggy', cn: '有雾的', category: 'weather', difficulty: 3 },
      { en: 'cool', cn: '凉爽的', category: 'weather', difficulty: 3 },
      // 时间短语 (8)
      { en: 'at noon', cn: '在中午', category: 'time_phrase', difficulty: 3, phrase: 'at noon', sentence: 'We have lunch at noon.' },
      { en: 'at night', cn: '在晚上', category: 'time_phrase', difficulty: 3, phrase: 'at night', sentence: 'I go to bed at night.' },
      { en: 'in the morning', cn: '在早上', category: 'time_phrase', difficulty: 3, phrase: 'in the morning', sentence: 'I read books in the morning.' },
      { en: 'every day', cn: '每天', category: 'time_phrase', difficulty: 3, phrase: 'every day', sentence: 'I go to school every day.' },
      { en: 'next to', cn: '在旁边', category: 'direction_phrase', difficulty: 3, phrase: 'next to', sentence: 'The school is next to the park.' },
      { en: 'in front of', cn: '在前面', category: 'direction_phrase', difficulty: 3, phrase: 'in front of', sentence: 'There is a tree in front of the house.' },
      { en: 'after school', cn: '放学后', category: 'time_phrase', difficulty: 3, phrase: 'after school', sentence: 'I play football after school.' },
      { en: 'on time', cn: '准时', category: 'time_phrase', difficulty: 3, phrase: 'on time', sentence: 'Please come to school on time.' },
      // 地点 (10)
      { en: 'park', cn: '公园', category: 'place', difficulty: 3 },
      { en: 'zoo', cn: '动物园', category: 'place', difficulty: 3 },
      { en: 'library', cn: '图书馆', category: 'place', difficulty: 3 },
      { en: 'hospital', cn: '医院', category: 'place', difficulty: 3 },
      { en: 'supermarket', cn: '超市', category: 'place', difficulty: 3 },
      { en: 'restaurant', cn: '餐厅', category: 'place', difficulty: 3 },
      { en: 'bank', cn: '银行', category: 'place', difficulty: 3 },
      { en: 'cinema', cn: '电影院', category: 'place', difficulty: 3 },
      { en: 'museum', cn: '博物馆', category: 'place', difficulty: 3 },
      { en: 'station', cn: '车站', category: 'place', difficulty: 3 },
      // 形容词扩展 (4)
      { en: 'fast', cn: '快的', category: 'adjective', difficulty: 3 },
      { en: 'slow', cn: '慢的', category: 'adjective', difficulty: 3 },
      { en: 'heavy', cn: '重的', category: 'adjective', difficulty: 3 },
      { en: 'light', cn: '轻的', category: 'adjective', difficulty: 3 }
    ]
  },

  4: {
    name: 'Level 4',
    theme: '职业·交通·自然·情感·购物·餐饮·国家·城市·节日·爱好',
    words: [
      // 职业 (12)
      { en: 'doctor', cn: '医生', category: 'occupation', difficulty: 4 },
      { en: 'nurse', cn: '护士', category: 'occupation', difficulty: 4 },
      { en: 'pilot', cn: '飞行员', category: 'occupation', difficulty: 4 },
      { en: 'farmer', cn: '农民', category: 'occupation', difficulty: 4 },
      { en: 'scientist', cn: '科学家', category: 'occupation', difficulty: 4 },
      { en: 'engineer', cn: '工程师', category: 'occupation', difficulty: 4 },
      { en: 'reporter', cn: '记者', category: 'occupation', difficulty: 4 },
      { en: 'astronaut', cn: '宇航员', category: 'occupation', difficulty: 4 },
      { en: 'musician', cn: '音乐家', category: 'occupation', difficulty: 4 },
      { en: 'artist', cn: '艺术家', category: 'occupation', difficulty: 4 },
      { en: 'firefighter', cn: '消防员', category: 'occupation', difficulty: 4 },
      { en: 'postman', cn: '邮递员', category: 'occupation', difficulty: 4 },
      // 交通 (10)
      { en: 'bus', cn: '公共汽车', category: 'transport', difficulty: 4 },
      { en: 'train', cn: '火车', category: 'transport', difficulty: 4 },
      { en: 'subway', cn: '地铁', category: 'transport', difficulty: 4 },
      { en: 'airplane', cn: '飞机', category: 'transport', difficulty: 4 },
      { en: 'bicycle', cn: '自行车', category: 'transport', difficulty: 4 },
      { en: 'taxi', cn: '出租车', category: 'transport', difficulty: 4 },
      { en: 'ship', cn: '轮船', category: 'transport', difficulty: 4 },
      { en: 'car', cn: '小汽车', category: 'transport', difficulty: 4 },
      { en: 'boat', cn: '小船', category: 'transport', difficulty: 4 },
      { en: 'helicopter', cn: '直升机', category: 'transport', difficulty: 4 },
      // 自然 (12)
      { en: 'river', cn: '河流', category: 'nature', difficulty: 4 },
      { en: 'mountain', cn: '山', category: 'nature', difficulty: 4 },
      { en: 'forest', cn: '森林', category: 'nature', difficulty: 4 },
      { en: 'ocean', cn: '海洋', category: 'nature', difficulty: 4 },
      { en: 'island', cn: '岛屿', category: 'nature', difficulty: 4 },
      { en: 'lake', cn: '湖', category: 'nature', difficulty: 4 },
      { en: 'field', cn: '田野', category: 'nature', difficulty: 4 },
      { en: 'desert', cn: '沙漠', category: 'nature', difficulty: 4 },
      { en: 'rainforest', cn: '雨林', category: 'nature', difficulty: 4 },
      { en: 'waterfall', cn: '瀑布', category: 'nature', difficulty: 4 },
      { en: 'valley', cn: '山谷', category: 'nature', difficulty: 4 },
      { en: 'volcano', cn: '火山', category: 'nature', difficulty: 4 },
      // 情感 (12)
      { en: 'love', cn: '爱', category: 'emotion', difficulty: 4 },
      { en: 'angry', cn: '生气的', category: 'emotion', difficulty: 4 },
      { en: 'sad', cn: '伤心的', category: 'emotion', difficulty: 4 },
      { en: 'excited', cn: '兴奋的', category: 'emotion', difficulty: 4 },
      { en: 'afraid', cn: '害怕的', category: 'emotion', difficulty: 4 },
      { en: 'proud', cn: '自豪的', category: 'emotion', difficulty: 4 },
      { en: 'surprised', cn: '惊讶的', category: 'emotion', difficulty: 4 },
      { en: 'worried', cn: '担心的', category: 'emotion', difficulty: 4 },
      { en: 'tired', cn: '累的', category: 'emotion', difficulty: 4 },
      { en: 'hungry', cn: '饿的', category: 'emotion', difficulty: 4 },
      { en: 'thirsty', cn: '渴的', category: 'emotion', difficulty: 4 },
      { en: 'bored', cn: '无聊的', category: 'emotion', difficulty: 4 },
      // 购物 (8)
      { en: 'shop', cn: '商店', category: 'shopping', difficulty: 4 },
      { en: 'price', cn: '价格', category: 'shopping', difficulty: 4 },
      { en: 'cheap', cn: '便宜的', category: 'shopping', difficulty: 4 },
      { en: 'expensive', cn: '贵的', category: 'shopping', difficulty: 4 },
      { en: 'buy', cn: '买', category: 'shopping', difficulty: 4 },
      { en: 'sell', cn: '卖', category: 'shopping', difficulty: 4 },
      { en: 'pay', cn: '付款', category: 'shopping', difficulty: 4 },
      { en: 'change', cn: '零钱', category: 'shopping', difficulty: 4 },
      // 餐饮 (8)
      { en: 'menu', cn: '菜单', category: 'dining', difficulty: 4 },
      { en: 'order', cn: '点餐', category: 'dining', difficulty: 4 },
      { en: 'waiter', cn: '服务员', category: 'dining', difficulty: 4 },
      { en: 'taste', cn: '味道', category: 'dining', difficulty: 4 },
      { en: 'delicious', cn: '美味的', category: 'dining', difficulty: 4 },
      { en: 'breakfast', cn: '早餐', category: 'dining', difficulty: 4 },
      { en: 'lunch', cn: '午餐', category: 'dining', difficulty: 4 },
      { en: 'dinner', cn: '晚餐', category: 'dining', difficulty: 4 },
      // 国家 (6)
      { en: 'China', cn: '中国', category: 'country', difficulty: 4 },
      { en: 'Japan', cn: '日本', category: 'country', difficulty: 4 },
      { en: 'USA', cn: '美国', category: 'country', difficulty: 4 },
      { en: 'UK', cn: '英国', category: 'country', difficulty: 4 },
      { en: 'France', cn: '法国', category: 'country', difficulty: 4 },
      { en: 'Australia', cn: '澳大利亚', category: 'country', difficulty: 4 },
      // 城市 (6)
      { en: 'Beijing', cn: '北京', category: 'city', difficulty: 4 },
      { en: 'Shanghai', cn: '上海', category: 'city', difficulty: 4 },
      { en: 'London', cn: '伦敦', category: 'city', difficulty: 4 },
      { en: 'New York', cn: '纽约', category: 'city', difficulty: 4 },
      { en: 'Paris', cn: '巴黎', category: 'city', difficulty: 4 },
      { en: 'Tokyo', cn: '东京', category: 'city', difficulty: 4 },
      // 节日 (8)
      { en: 'Christmas', cn: '圣诞节', category: 'festival', difficulty: 4 },
      { en: 'New Year', cn: '新年', category: 'festival', difficulty: 4 },
      { en: 'Spring Festival', cn: '春节', category: 'festival', difficulty: 4 },
      { en: 'Mid-Autumn Festival', cn: '中秋节', category: 'festival', difficulty: 4 },
      { en: 'birthday', cn: '生日', category: 'festival', difficulty: 4 },
      { en: 'Children\'s Day', cn: '儿童节', category: 'festival', difficulty: 4 },
      { en: 'Mother\'s Day', cn: '母亲节', category: 'festival', difficulty: 4 },
      { en: 'National Day', cn: '国庆节', category: 'festival', difficulty: 4 },
      // 爱好 (10)
      { en: 'hobby', cn: '爱好', category: 'hobby', difficulty: 4 },
      { en: 'reading', cn: '阅读', category: 'hobby', difficulty: 4 },
      { en: 'drawing', cn: '画画', category: 'hobby', difficulty: 4 },
      { en: 'singing', cn: '唱歌', category: 'hobby', difficulty: 4 },
      { en: 'dancing', cn: '跳舞', category: 'hobby', difficulty: 4 },
      { en: 'cooking', cn: '烹饪', category: 'hobby', difficulty: 4 },
      { en: 'gardening', cn: '园艺', category: 'hobby', difficulty: 4 },
      { en: 'photography', cn: '摄影', category: 'hobby', difficulty: 4 },
      { en: 'collecting', cn: '收集', category: 'hobby', difficulty: 4 },
      { en: 'camping', cn: '露营', category: 'hobby', difficulty: 4 },
      // 情感/动作短语 (12)
      { en: 'have fun', cn: '玩得开心', category: 'emotion_phrase', difficulty: 4, phrase: 'have fun', sentence: 'Have fun at the party!' },
      { en: 'take care', cn: '保重', category: 'emotion_phrase', difficulty: 4, phrase: 'take care', sentence: 'Take care of yourself.' },
      { en: 'cheer up', cn: '振作起来', category: 'emotion_phrase', difficulty: 4, phrase: 'cheer up', sentence: 'Cheer up! Everything will be fine.' },
      { en: 'behind', cn: '在后面', category: 'direction', difficulty: 4, phrase: 'behind', sentence: 'The cat is behind the door.' },
      { en: 'between', cn: '在之间', category: 'direction', difficulty: 4, phrase: 'between', sentence: 'The book is between the pens.' },
      { en: 'under', cn: '在下面', category: 'direction', difficulty: 4, phrase: 'under', sentence: 'The ball is under the chair.' },
      { en: 'on the left', cn: '在左边', category: 'direction_phrase', difficulty: 4, phrase: 'on the left', sentence: 'The library is on the left.' },
      { en: 'on the right', cn: '在右边', category: 'direction_phrase', difficulty: 4, phrase: 'on the right', sentence: 'The hospital is on the right.' },
      { en: 'go straight', cn: '直走', category: 'direction_phrase', difficulty: 4, phrase: 'go straight', sentence: 'Go straight and turn left.' },
      { en: 'turn left', cn: '左转', category: 'direction_phrase', difficulty: 4, phrase: 'turn left', sentence: 'Turn left at the traffic light.' },
      { en: 'turn right', cn: '右转', category: 'direction_phrase', difficulty: 4, phrase: 'turn right', sentence: 'Turn right at the corner.' },
      { en: 'traffic light', cn: '红绿灯', category: 'direction_phrase', difficulty: 4, phrase: 'traffic light', sentence: 'Stop at the red traffic light.' },
      // 自然/环境短语 (6)
      { en: 'air pollution', cn: '空气污染', category: 'environment', difficulty: 4, phrase: 'air pollution', sentence: 'Air pollution is bad for our health.' },
      { en: 'save water', cn: '节约用水', category: 'environment', difficulty: 4, phrase: 'save water', sentence: 'We should save water.' },
      { en: 'plant trees', cn: '植树', category: 'environment', difficulty: 4, phrase: 'plant trees', sentence: 'We plant trees on Tree Planting Day.' },
      { en: 'recycle', cn: '回收利用', category: 'environment', difficulty: 4, phrase: 'recycle', sentence: 'Please recycle paper and plastic.' },
      { en: 'protect', cn: '保护', category: 'environment', difficulty: 4, phrase: 'protect', sentence: 'We should protect animals.' },
      { en: 'nature', cn: '大自然', category: 'environment', difficulty: 4, phrase: 'nature', sentence: 'Nature is beautiful.' },
      // 交通扩展 (8)
      { en: 'traffic', cn: '交通', category: 'transport', difficulty: 4, sentence: 'There is a lot of traffic.' },
      { en: 'station', cn: '车站', category: 'transport', difficulty: 4, sentence: 'The bus station is near here.' },
      { en: 'airport', cn: '机场', category: 'transport', difficulty: 4, sentence: 'We go to the airport by taxi.' },
      { en: 'ticket', cn: '票', category: 'transport', difficulty: 4, sentence: 'I need to buy a train ticket.' },
      { en: 'travel', cn: '旅行', category: 'transport', difficulty: 4, sentence: 'I want to travel around the world.' },
      { en: 'drive', cn: '开车', category: 'transport', difficulty: 4, sentence: 'My father drives me to school.' },
      { en: 'ride', cn: '骑', category: 'transport', difficulty: 4, sentence: 'I can ride a bicycle.' },
      { en: 'by bus', cn: '乘公交', category: 'transport', difficulty: 4, phrase: 'by bus', sentence: 'I go to school by bus.' },
      // 购物扩展 (2)
      { en: 'customer', cn: '顾客', category: 'shopping', difficulty: 4, sentence: 'The customer wants to buy a shirt.' },
      { en: 'receipt', cn: '收据', category: 'shopping', difficulty: 4, sentence: 'Please keep your receipt.' }
    ]
  },

  5: {
    name: 'Level 5',
    theme: '抽象概念·复合词·惯用语·健康·环境·比较级·不规则动词·情感扩展',
    words: [
      // 抽象概念 (10)
      { en: 'freedom', cn: '自由', category: 'abstract', difficulty: 5 },
      { en: 'success', cn: '成功', category: 'abstract', difficulty: 5 },
      { en: 'knowledge', cn: '知识', category: 'abstract', difficulty: 5 },
      { en: 'courage', cn: '勇气', category: 'abstract', difficulty: 5 },
      { en: 'peace', cn: '和平', category: 'abstract', difficulty: 5 },
      { en: 'honesty', cn: '诚实', category: 'abstract', difficulty: 5 },
      { en: 'wisdom', cn: '智慧', category: 'abstract', difficulty: 5, sentence: 'Knowledge comes from learning, wisdom comes from life.' },
      { en: 'justice', cn: '正义', category: 'abstract', difficulty: 5, sentence: 'Everyone deserves justice.' },
      { en: 'patience', cn: '耐心', category: 'abstract', difficulty: 5, sentence: 'You need patience to learn a language.' },
      { en: 'confidence', cn: '自信', category: 'abstract', difficulty: 5, sentence: 'She has great confidence in her English.' },
      // 复合词 (10)
      { en: 'sunflower', cn: '向日葵', category: 'compound', difficulty: 5 },
      { en: 'rainbow', cn: '彩虹', category: 'compound', difficulty: 5 },
      { en: 'football', cn: '足球', category: 'compound', difficulty: 5 },
      { en: 'birthday', cn: '生日', category: 'compound', difficulty: 5 },
      { en: 'daylight', cn: '日光', category: 'compound', difficulty: 5 },
      { en: 'notebook', cn: '笔记本', category: 'compound', difficulty: 5 },
      { en: 'schoolbag', cn: '书包', category: 'compound', difficulty: 5, sentence: 'I put my books in my schoolbag.' },
      { en: 'classroom', cn: '教室', category: 'compound', difficulty: 5, sentence: 'Our classroom is on the second floor.' },
      { en: 'playground', cn: '操场', category: 'compound', difficulty: 5, sentence: 'The children are playing on the playground.' },
      { en: 'everyone', cn: '每个人', category: 'compound', difficulty: 5, sentence: 'Everyone in our class likes English.' },
      // 惯用语 (12)
      { en: 'piece of cake', cn: '小菜一碟', category: 'idiom', difficulty: 5 },
      { en: 'break a leg', cn: '祝好运', category: 'idiom', difficulty: 5 },
      { en: 'let it go', cn: '顺其自然', category: 'idiom', difficulty: 5 },
      { en: 'no pain no gain', cn: '不劳无获', category: 'idiom', difficulty: 5 },
      { en: 'on time', cn: '准时', category: 'idiom', difficulty: 5 },
      { en: 'all right', cn: '好的', category: 'idiom', difficulty: 5 },
      { en: 'once upon a time', cn: '从前', category: 'idiom', difficulty: 5, phrase: 'once upon a time', sentence: 'Once upon a time, there was a princess...' },
      { en: 'as usual', cn: '像往常一样', category: 'idiom', difficulty: 5, phrase: 'as usual', sentence: 'He arrived late as usual.' },
      { en: 'in a hurry', cn: '匆忙', category: 'idiom', difficulty: 5, phrase: 'in a hurry', sentence: 'She left in a hurry.' },
      { en: 'by the way', cn: '顺便说一下', category: 'idiom', difficulty: 5, phrase: 'by the way', sentence: 'By the way, do you like music?' },
      { en: 'in a word', cn: '总之', category: 'idiom', difficulty: 5, phrase: 'in a word', sentence: 'In a word, we need to work harder.' },
      { en: 'at first', cn: '起初', category: 'idiom', difficulty: 5, phrase: 'at first', sentence: 'At first, I didn\'t like English.' },
      // 健康 (10)
      { en: 'health', cn: '健康', category: 'health', difficulty: 5 },
      { en: 'exercise', cn: '锻炼', category: 'health', difficulty: 5 },
      { en: 'medicine', cn: '药', category: 'health', difficulty: 5 },
      { en: 'rest', cn: '休息', category: 'health', difficulty: 5 },
      { en: 'sleep', cn: '睡觉', category: 'health', difficulty: 5 },
      { en: 'body', cn: '身体', category: 'health', difficulty: 5 },
      { en: 'energy', cn: '精力', category: 'health', difficulty: 5, sentence: 'Eating well gives you energy.' },
      { en: 'vitamin', cn: '维生素', category: 'health', difficulty: 5, sentence: 'Fruit contains many vitamins.' },
      { en: 'fever', cn: '发烧', category: 'health', difficulty: 5 },
      { en: 'cold', cn: '感冒', category: 'health', difficulty: 5, sentence: 'I caught a cold last week.' },
      // 环境 (10)
      { en: 'environment', cn: '环境', category: 'environment', difficulty: 5 },
      { en: 'pollution', cn: '污染', category: 'environment', difficulty: 5 },
      { en: 'recycle', cn: '回收', category: 'environment', difficulty: 5 },
      { en: 'energy', cn: '能源', category: 'environment', difficulty: 5 },
      { en: 'global warming', cn: '全球变暖', category: 'environment', difficulty: 5, sentence: 'Global warming is a serious problem.' },
      { en: 'greenhouse', cn: '温室', category: 'environment', difficulty: 5, sentence: 'Greenhouse gases cause climate change.' },
      { en: 'solar', cn: '太阳能的', category: 'environment', difficulty: 5, sentence: 'Solar energy is clean energy.' },
      { en: 'plastic', cn: '塑料', category: 'environment', difficulty: 5, sentence: 'We should reduce plastic waste.' },
      { en: 'garbage', cn: '垃圾', category: 'environment', difficulty: 5 },
      { en: 'earth', cn: '地球', category: 'environment', difficulty: 5, sentence: 'We should protect the earth.' },
      // 比较级 (10)
      { en: 'bigger', cn: '更大的', category: 'comparative', difficulty: 5, sentence: 'My house is bigger than yours.' },
      { en: 'smaller', cn: '更小的', category: 'comparative', difficulty: 5, sentence: 'A mouse is smaller than a cat.' },
      { en: 'faster', cn: '更快的', category: 'comparative', difficulty: 5, sentence: 'He runs faster than me.' },
      { en: 'slower', cn: '更慢的', category: 'comparative', difficulty: 5, sentence: 'The bus is slower than the train.' },
      { en: 'better', cn: '更好的', category: 'comparative', difficulty: 5, sentence: 'Practice makes you better.' },
      { en: 'worse', cn: '更差的', category: 'comparative', difficulty: 5, sentence: 'The weather is worse today.' },
      { en: 'more', cn: '更多的', category: 'comparative', difficulty: 5, sentence: 'I need more time.' },
      { en: 'less', cn: '更少的', category: 'comparative', difficulty: 5, sentence: 'I have less money than you.' },
      { en: 'the best', cn: '最好的', category: 'comparative', difficulty: 5, sentence: 'She is the best student.' },
      { en: 'the most', cn: '最多的', category: 'comparative', difficulty: 5, sentence: 'This is the most beautiful park.' },
      // 不规则动词 (10)
      { en: 'go-went', cn: '去(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I went to the park yesterday.' },
      { en: 'eat-ate', cn: '吃(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I ate an apple for breakfast.' },
      { en: 'see-saw', cn: '看见(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I saw a movie last night.' },
      { en: 'buy-bought', cn: '买(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I bought a new book.' },
      { en: 'have-had', cn: '有(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I had a great time.' },
      { en: 'take-took', cn: '拿(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I took a photo.' },
      { en: 'make-made', cn: '做(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I made a cake.' },
      { en: 'say-said', cn: '说(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'He said hello to me.' },
      { en: 'come-came', cn: '来(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'She came to my party.' },
      { en: 'give-gave', cn: '给(过去式)', category: 'irregular_verb', difficulty: 5, sentence: 'I gave her a gift.' },
      // 情感词汇扩展 (10)
      { en: 'amazing', cn: '令人惊奇的', category: 'emotion', difficulty: 5, sentence: 'The view is amazing!' },
      { en: 'wonderful', cn: '精彩的', category: 'emotion', difficulty: 5, sentence: 'What a wonderful day!' },
      { en: 'terrible', cn: '糟糕的', category: 'emotion', difficulty: 5, sentence: 'The weather is terrible.' },
      { en: 'nervous', cn: '紧张的', category: 'emotion', difficulty: 5, sentence: 'I feel nervous before the exam.' },
      { en: 'lonely', cn: '孤独的', category: 'emotion', difficulty: 5, sentence: 'He feels lonely without friends.' },
      { en: 'grateful', cn: '感激的', category: 'emotion', difficulty: 5, sentence: 'I am grateful for your help.' },
      { en: 'brave', cn: '勇敢的', category: 'emotion', difficulty: 5, sentence: 'Be brave and try again.' },
      { en: 'curious', cn: '好奇的', category: 'emotion', difficulty: 5, sentence: 'Children are curious about everything.' },
      { en: 'jealous', cn: '嫉妒的', category: 'emotion', difficulty: 5, sentence: 'Don\'t be jealous of others.' },
      { en: 'shy', cn: '害羞的', category: 'emotion', difficulty: 5, sentence: 'She is shy when meeting new people.' },
      // 抽象扩展 (8)
      { en: 'imagination', cn: '想象力', category: 'abstract', difficulty: 5, sentence: 'Reading helps develop imagination.' },
      { en: 'responsibility', cn: '责任', category: 'abstract', difficulty: 5, sentence: 'We have a responsibility to help others.' },
      { en: 'opportunity', cn: '机会', category: 'abstract', difficulty: 5, sentence: 'Don\'t miss this opportunity.' },
      { en: 'experience', cn: '经历/经验', category: 'abstract', difficulty: 5, sentence: 'Travel gives you new experiences.' },
      { en: 'memory', cn: '记忆', category: 'abstract', difficulty: 5, sentence: 'I have happy memories of my childhood.' },
      { en: 'decision', cn: '决定', category: 'abstract', difficulty: 5, sentence: 'Think before you make a decision.' },
      { en: 'difference', cn: '不同', category: 'abstract', difficulty: 5, sentence: 'Can you tell the difference?' },
      { en: 'future', cn: '未来', category: 'abstract', difficulty: 5, sentence: 'What do you want to be in the future?' },
      // 复合词扩展 (8)
      { en: 'understand', cn: '理解', category: 'compound', difficulty: 5, sentence: 'I don\'t understand this question.' },
      { en: 'weekend', cn: '周末', category: 'compound', difficulty: 5, sentence: 'What do you do on weekends?' },
      { en: 'mooncake', cn: '月饼', category: 'compound', difficulty: 5, sentence: 'We eat mooncakes at Mid-Autumn Festival.' },
      { en: 'earthquake', cn: '地震', category: 'compound', difficulty: 5, sentence: 'Earthquakes can be very dangerous.' },
      { en: 'starlight', cn: '星光', category: 'compound', difficulty: 5, sentence: 'The starlight is beautiful tonight.' },
      { en: 'seaside', cn: '海边', category: 'compound', difficulty: 5, sentence: 'We went to the seaside last summer.' },
      { en: 'upstairs', cn: '楼上', category: 'compound', difficulty: 5, sentence: 'She is sleeping upstairs.' },
      { en: 'downstairs', cn: '楼下', category: 'compound', difficulty: 5, sentence: 'Come downstairs for dinner.' },
      // 惯用语扩展 (10)
      { en: 'so far', cn: '到目前为止', category: 'idiom', difficulty: 5, phrase: 'so far', sentence: 'So far, everything is going well.' },
      { en: 'at least', cn: '至少', category: 'idiom', difficulty: 5, phrase: 'at least', sentence: 'You should read at least 30 minutes a day.' },
      { en: 'in fact', cn: '事实上', category: 'idiom', difficulty: 5, phrase: 'in fact', sentence: 'In fact, English is not that hard.' },
      { en: 'for example', cn: '例如', category: 'idiom', difficulty: 5, phrase: 'for example', sentence: 'For example, apples and bananas are fruits.' },
      { en: 'more or less', cn: '或多或少', category: 'idiom', difficulty: 5, phrase: 'more or less', sentence: 'I have more or less finished my homework.' },
      { en: 'once more', cn: '再一次', category: 'idiom', difficulty: 5, phrase: 'once more', sentence: 'Please say it once more.' },
      { en: 'all day', cn: '整天', category: 'idiom', difficulty: 5, phrase: 'all day', sentence: 'It rained all day.' },
      { en: 'in the end', cn: '最后', category: 'idiom', difficulty: 5, phrase: 'in the end', sentence: 'In the end, we found the way.' },
      { en: 'after all', cn: '毕竟', category: 'idiom', difficulty: 5, phrase: 'after all', sentence: 'Don\'t be angry with him. After all, he is a child.' },
      { en: 'no matter', cn: '无论', category: 'idiom', difficulty: 5, phrase: 'no matter', sentence: 'No matter what happens, don\'t give up.' },
      // 动词短语扩展 (6)
      { en: 'give up', cn: '放弃', category: 'verb_phrase', difficulty: 5, phrase: 'give up', sentence: 'Never give up on your dreams.' },
      { en: 'wake up', cn: '醒来', category: 'verb_phrase', difficulty: 5, phrase: 'wake up', sentence: 'I wake up at 6 o\'clock every morning.' },
      { en: 'pick up', cn: '捡起/接人', category: 'verb_phrase', difficulty: 5, phrase: 'pick up', sentence: 'Please pick up the trash.' },
      { en: 'look for', cn: '寻找', category: 'verb_phrase', difficulty: 5, phrase: 'look for', sentence: 'I am looking for my keys.' },
      { en: 'wait for', cn: '等待', category: 'verb_phrase', difficulty: 5, phrase: 'wait for', sentence: 'Please wait for me.' },
      { en: 'talk about', cn: '谈论', category: 'verb_phrase', difficulty: 5, phrase: 'talk about', sentence: 'Let\'s talk about the plan.' },
      // 形容词扩展 (6)
      { en: 'useful', cn: '有用的', category: 'adjective', difficulty: 5, sentence: 'This book is very useful.' },
      { en: 'careful', cn: '小心的', category: 'adjective', difficulty: 5, sentence: 'Be careful when you cross the street.' },
      { en: 'helpful', cn: '有帮助的', category: 'adjective', difficulty: 5, sentence: 'She is always helpful to others.' },
      { en: 'wonderful', cn: '精彩的', category: 'adjective', difficulty: 5, sentence: 'What a wonderful day!' },
      { en: 'peaceful', cn: '和平的/宁静的', category: 'adjective', difficulty: 5, sentence: 'The park is very peaceful.' },
      { en: 'colorful', cn: '多彩的', category: 'adjective', difficulty: 5, sentence: 'The flowers are very colorful.' }
    ]
  },

  6: {
    name: 'Level 6',
    theme: '学术词汇·复杂句型·社会·科技·文化·连接词·综合表达',
    words: [
      // 学术词汇 (14)
      { en: 'experiment', cn: '实验', category: 'academic', difficulty: 6 },
      { en: 'development', cn: '发展', category: 'academic', difficulty: 6 },
      { en: 'government', cn: '政府', category: 'academic', difficulty: 6 },
      { en: 'education', cn: '教育', category: 'academic', difficulty: 6 },
      { en: 'technology', cn: '技术', category: 'academic', difficulty: 6 },
      { en: 'population', cn: '人口', category: 'academic', difficulty: 6 },
      { en: 'communication', cn: '交流', category: 'academic', difficulty: 6 },
      { en: 'discovery', cn: '发现', category: 'academic', difficulty: 6, sentence: 'This discovery changed the world.' },
      { en: 'invention', cn: '发明', category: 'academic', difficulty: 6, sentence: 'The invention of the internet changed everything.' },
      { en: 'knowledge', cn: '知识', category: 'academic', difficulty: 6, sentence: 'Knowledge is power.' },
      { en: 'achievement', cn: '成就', category: 'academic', difficulty: 6, sentence: 'This is a great achievement.' },
      { en: 'responsibility', cn: '责任', category: 'academic', difficulty: 6, sentence: 'We have a responsibility to protect nature.' },
      { en: 'research', cn: '研究', category: 'academic', difficulty: 6, sentence: 'Scientists do research to find answers.' },
      { en: 'analysis', cn: '分析', category: 'academic', difficulty: 6, sentence: 'We need to do a careful analysis.' },
      // 复杂句型 (14)
      { en: 'I think that', cn: '我认为', category: 'sentence', difficulty: 6 },
      { en: 'make a decision', cn: '做决定', category: 'sentence', difficulty: 6 },
      { en: 'take part in', cn: '参加', category: 'sentence', difficulty: 6 },
      { en: 'look forward to', cn: '期待', category: 'sentence', difficulty: 6 },
      { en: 'be good at', cn: '擅长', category: 'sentence', difficulty: 6 },
      { en: 'get along with', cn: '与…相处', category: 'sentence', difficulty: 6 },
      { en: 'as soon as', cn: '一…就…', category: 'sentence', difficulty: 6 },
      { en: 'in addition', cn: '此外', category: 'sentence', difficulty: 6 },
      { en: 'on the other hand', cn: '另一方面', category: 'sentence', difficulty: 6 },
      { en: 'in my opinion', cn: '在我看来', category: 'sentence', difficulty: 6, phrase: 'in my opinion', sentence: 'In my opinion, English is very useful.' },
      { en: 'as a result', cn: '因此', category: 'sentence', difficulty: 6, phrase: 'as a result', sentence: 'He studied hard. As a result, he passed the exam.' },
      { en: 'in conclusion', cn: '总之', category: 'sentence', difficulty: 6, phrase: 'in conclusion', sentence: 'In conclusion, we should practice every day.' },
      { en: 'first of all', cn: '首先', category: 'sentence', difficulty: 6, phrase: 'first of all', sentence: 'First of all, let me introduce myself.' },
      { en: 'more importantly', cn: '更重要的是', category: 'sentence', difficulty: 6, phrase: 'more importantly', sentence: 'More importantly, you need to enjoy learning.' },
      // 社会 (12)
      { en: 'society', cn: '社会', category: 'society', difficulty: 6, sentence: 'We live in a modern society.' },
      { en: 'community', cn: '社区', category: 'society', difficulty: 6, sentence: 'There is a park in our community.' },
      { en: 'culture', cn: '文化', category: 'society', difficulty: 6, sentence: 'We should learn about different cultures.' },
      { en: 'tradition', cn: '传统', category: 'society', difficulty: 6, sentence: 'Spring Festival is an important tradition.' },
      { en: 'history', cn: '历史', category: 'society', difficulty: 6, sentence: 'China has a long history.' },
      { en: 'economy', cn: '经济', category: 'society', difficulty: 6, sentence: 'Our country\'s economy is growing.' },
      { en: 'volunteer', cn: '志愿者', category: 'society', difficulty: 6, sentence: 'I want to be a volunteer.' },
      { en: 'charity', cn: '慈善', category: 'society', difficulty: 6, sentence: 'We should support charity work.' },
      { en: 'equality', cn: '平等', category: 'society', difficulty: 6, sentence: 'Everyone deserves equality.' },
      { en: 'law', cn: '法律', category: 'society', difficulty: 6, sentence: 'Everyone must follow the law.' },
      { en: 'right', cn: '权利', category: 'society', difficulty: 6, sentence: 'Every child has the right to education.' },
      { en: 'duty', cn: '义务', category: 'society', difficulty: 6, sentence: 'It is our duty to protect the environment.' },
      // 科技 (12)
      { en: 'internet', cn: '互联网', category: 'technology', difficulty: 6, sentence: 'The internet connects people around the world.' },
      { en: 'computer', cn: '计算机', category: 'technology', difficulty: 6, sentence: 'I use a computer for my homework.' },
      { en: 'website', cn: '网站', category: 'technology', difficulty: 6, sentence: 'We can find information on websites.' },
      { en: 'digital', cn: '数字的', category: 'technology', difficulty: 6, sentence: 'Digital cameras are popular.' },
      { en: 'robot', cn: '机器人', category: 'technology', difficulty: 6, sentence: 'Robots can help us do housework.' },
      { en: 'satellite', cn: '卫星', category: 'technology', difficulty: 6, sentence: 'Satellites help us navigate.' },
      { en: 'software', cn: '软件', category: 'technology', difficulty: 6, sentence: 'This software is very useful.' },
      { en: 'app', cn: '应用程序', category: 'technology', difficulty: 6, sentence: 'There is an app for learning English.' },
      { en: 'program', cn: '程序', category: 'technology', difficulty: 6, sentence: 'I am learning to write computer programs.' },
      { en: 'data', cn: '数据', category: 'technology', difficulty: 6, sentence: 'We collect data for the experiment.' },
      { en: 'network', cn: '网络', category: 'technology', difficulty: 6, sentence: 'The whole network is connected.' },
      { en: 'AI', cn: '人工智能', category: 'technology', difficulty: 6, sentence: 'AI is changing our lives.' },
      // 文化 (10)
      { en: 'festival', cn: '节日', category: 'culture', difficulty: 6, sentence: 'We celebrate many festivals.' },
      { en: 'celebrate', cn: '庆祝', category: 'culture', difficulty: 6, sentence: 'How do you celebrate Spring Festival?' },
      { en: 'costume', cn: '服装/戏服', category: 'culture', difficulty: 6, sentence: 'They wore beautiful costumes.' },
      { en: 'custom', cn: '风俗', category: 'culture', difficulty: 6, sentence: 'Every country has its own customs.' },
      { en: 'language', cn: '语言', category: 'culture', difficulty: 6, sentence: 'Learning a language takes time.' },
      { en: 'folk tale', cn: '民间故事', category: 'culture', difficulty: 6, sentence: 'I love reading Chinese folk tales.' },
      { en: 'art', cn: '艺术', category: 'culture', difficulty: 6, sentence: 'Painting is a form of art.' },
      { en: 'music', cn: '音乐', category: 'culture', difficulty: 6, sentence: 'Music makes the world beautiful.' },
      { en: 'literature', cn: '文学', category: 'culture', difficulty: 6, sentence: 'We study literature in English class.' },
      { en: 'poem', cn: '诗歌', category: 'culture', difficulty: 6, sentence: 'This poem is very beautiful.' },
      // 连接词 (12)
      { en: 'however', cn: '然而', category: 'conjunction', difficulty: 6, sentence: 'It was raining. However, we still went out.' },
      { en: 'therefore', cn: '因此', category: 'conjunction', difficulty: 6, sentence: 'He was sick. Therefore, he stayed home.' },
      { en: 'moreover', cn: '此外', category: 'conjunction', difficulty: 6, sentence: 'The book is interesting. Moreover, it is cheap.' },
      { en: 'otherwise', cn: '否则', category: 'conjunction', difficulty: 6, sentence: 'Hurry up, otherwise we\'ll be late.' },
      { en: 'although', cn: '虽然', category: 'conjunction', difficulty: 6, sentence: 'Although it was cold, we went outside.' },
      { en: 'unless', cn: '除非', category: 'conjunction', difficulty: 6, sentence: 'You won\'t pass unless you study hard.' },
      { en: 'neither', cn: '两者都不', category: 'conjunction', difficulty: 6, sentence: 'Neither answer is correct.' },
      { en: 'whether', cn: '是否', category: 'conjunction', difficulty: 6, sentence: 'I don\'t know whether he will come.' },
      { en: 'besides', cn: '除了', category: 'conjunction', difficulty: 6, sentence: 'Besides English, he also learns French.' },
      { en: 'instead', cn: '代替', category: 'conjunction', difficulty: 6, sentence: 'Let\'s play games instead of watching TV.' },
      { en: 'meanwhile', cn: '同时', category: 'conjunction', difficulty: 6, sentence: 'I was cooking. Meanwhile, the kids were playing.' },
      { en: 'finally', cn: '最后', category: 'conjunction', difficulty: 6, sentence: 'Finally, we arrived at the airport.' },
      // 学术词汇扩展 (16)
      { en: 'conclusion', cn: '结论', category: 'academic', difficulty: 6, sentence: 'What is your conclusion?' },
      { en: 'evidence', cn: '证据', category: 'academic', difficulty: 6, sentence: 'There is evidence to support this idea.' },
      { en: 'theory', cn: '理论', category: 'academic', difficulty: 6, sentence: 'We learned about the theory of gravity.' },
      { en: 'process', cn: '过程', category: 'academic', difficulty: 6, sentence: 'Learning is a life-long process.' },
      { en: 'method', cn: '方法', category: 'academic', difficulty: 6, sentence: 'This is a good method for learning words.' },
      { en: 'system', cn: '系统', category: 'academic', difficulty: 6, sentence: 'The education system is improving.' },
      { en: 'source', cn: '来源', category: 'academic', difficulty: 6, sentence: 'Check your information sources carefully.' },
      { en: 'factor', cn: '因素', category: 'academic', difficulty: 6, sentence: 'There are many factors that affect learning.' },
      { en: 'standard', cn: '标准', category: 'academic', difficulty: 6, sentence: 'We need to meet high standards.' },
      { en: 'structure', cn: '结构', category: 'academic', difficulty: 6, sentence: 'This sentence structure is complex.' },
      { en: 'function', cn: '功能', category: 'academic', difficulty: 6, sentence: 'What is the function of this machine?' },
      { en: 'strategy', cn: '策略', category: 'academic', difficulty: 6, sentence: 'We need a good strategy to win.' },
      { en: 'percentage', cn: '百分比', category: 'academic', difficulty: 6, sentence: 'What percentage of students passed?' },
      { en: 'resource', cn: '资源', category: 'academic', difficulty: 6, sentence: 'The internet is a great learning resource.' },
      { en: 'volume', cn: '量/音量', category: 'academic', difficulty: 6, sentence: 'Please turn up the volume.' },
      { en: 'principle', cn: '原理/原则', category: 'academic', difficulty: 6, sentence: 'We learned the basic principles of science.' },
      // 复杂句型扩展 (8)
      { en: 'be interested in', cn: '对…感兴趣', category: 'sentence', difficulty: 6, phrase: 'be interested in', sentence: 'I am interested in science.' },
      { en: 'be proud of', cn: '为…骄傲', category: 'sentence', difficulty: 6, phrase: 'be proud of', sentence: 'I am proud of my country.' },
      { en: 'be used to', cn: '习惯于', category: 'sentence', difficulty: 6, phrase: 'be used to', sentence: 'I am used to getting up early.' },
      { en: 'depend on', cn: '依赖/取决于', category: 'sentence', difficulty: 6, phrase: 'depend on', sentence: 'It depends on the weather.' },
      { en: 'deal with', cn: '处理', category: 'sentence', difficulty: 6, phrase: 'deal with', sentence: 'How do you deal with stress?' },
      { en: 'worry about', cn: '担心', category: 'sentence', difficulty: 6, phrase: 'worry about', sentence: 'Don\'t worry about the exam.' },
      { en: 'dream of', cn: '梦想', category: 'sentence', difficulty: 6, phrase: 'dream of', sentence: 'I dream of becoming a teacher.' },
      { en: 'believe in', cn: '相信', category: 'sentence', difficulty: 6, phrase: 'believe in', sentence: 'I believe in myself.' },
      // 惯用语扩展 (10)
      { en: 'on the contrary', cn: '相反', category: 'sentence', difficulty: 6, phrase: 'on the contrary', sentence: 'I\'m not tired. On the contrary, I feel great.' },
      { en: 'in other words', cn: '换句话说', category: 'sentence', difficulty: 6, phrase: 'in other words', sentence: 'In other words, practice makes perfect.' },
      { en: 'above all', cn: '最重要的是', category: 'sentence', difficulty: 6, phrase: 'above all', sentence: 'Above all, stay safe.' },
      { en: 'as well', cn: '也', category: 'sentence', difficulty: 6, phrase: 'as well', sentence: 'I like English and I like math as well.' },
      { en: 'at once', cn: '立刻', category: 'sentence', difficulty: 6, phrase: 'at once', sentence: 'Please come here at once.' },
      { en: 'by accident', cn: '偶然', category: 'sentence', difficulty: 6, phrase: 'by accident', sentence: 'I found the answer by accident.' },
      { en: 'in time', cn: '及时', category: 'sentence', difficulty: 6, phrase: 'in time', sentence: 'We arrived in time for the show.' },
      { en: 'in need', cn: '需要帮助', category: 'sentence', difficulty: 6, phrase: 'in need', sentence: 'A friend in need is a friend indeed.' },
      { en: 'on purpose', cn: '故意', category: 'sentence', difficulty: 6, phrase: 'on purpose', sentence: 'I didn\'t break it on purpose.' },
      { en: 'out of', cn: '从…出来/缺乏', category: 'sentence', difficulty: 6, phrase: 'out of', sentence: 'We are out of milk.' },
      // 形容词扩展 (12)
      { en: 'necessary', cn: '必要的', category: 'adjective', difficulty: 6, sentence: 'It is necessary to practice every day.' },
      { en: 'possible', cn: '可能的', category: 'adjective', difficulty: 6, sentence: 'Is it possible to finish today?' },
      { en: 'comfortable', cn: '舒适的', category: 'adjective', difficulty: 6, sentence: 'This chair is very comfortable.' },
      { en: 'important', cn: '重要的', category: 'adjective', difficulty: 6, sentence: 'Education is very important.' },
      { en: 'difficult', cn: '困难的', category: 'adjective', difficulty: 6, sentence: 'The exam was very difficult.' },
      { en: 'dangerous', cn: '危险的', category: 'adjective', difficulty: 6, sentence: 'It is dangerous to play in the street.' },
      { en: 'famous', cn: '著名的', category: 'adjective', difficulty: 6, sentence: 'This city is famous for its food.' },
      { en: 'popular', cn: '流行的', category: 'adjective', difficulty: 6, sentence: 'This song is very popular.' },
      { en: 'special', cn: '特别的', category: 'adjective', difficulty: 6, sentence: 'Today is a special day.' },
      { en: 'successful', cn: '成功的', category: 'adjective', difficulty: 6, sentence: 'She is a successful businesswoman.' },
      { en: 'traditional', cn: '传统的', category: 'adjective', difficulty: 6, sentence: 'We eat traditional food at Spring Festival.' },
      { en: 'international', cn: '国际的', category: 'adjective', difficulty: 6, sentence: 'English is an international language.' }
    ]
  }
};

/**
 * 根据等级获取词汇列表
 * @param {number} level 英语等级 (1-6)
 * @returns {Array} 词汇数组
 */
export function getWordsByLevel(level) {
  const config = englishGradesConfig[level];
  return config ? config.words : [];
}

/**
 * 根据等级获取等级名
 * @param {number} level
 * @returns {string}
 */
export function getLevelName(level) {
  const config = englishGradesConfig[level];
  return config ? config.name : '';
}
